// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type AuthorInput struct {
	Name string `json:"name"`
}

type Book struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Author *Author `json:"author"`
}

type BookInput struct {
	Title    string `json:"title"`
	AuthorID string `json:"authorId"`
}
